spring:
  application:
    name: inventory-warehouse

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: Password123!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080